["x/tld/TOTAL.html"]
deps=["tmp/TOTAL.json", "build/make.js"]
exec="node build/make"

["tmp/TOTAL.json"]
deps=["build/hashtag.js", "tmp/instances.js"]
exec="node build/hashtag"

["tmp/instances.js"]
deps=["tmp/instances.html","build/html2js.js"]
exec="node build/html2js tmp/instances.html > $@"

["tmp/instances.html"]
exec="wget https://mastodon.fediverse.observer/app/views/tabledata.php?software=mastodon -O $@"

[publish]
deps=["x/tld/TOTAL.html"]
exec="git add x/content.html x/distances.html x/tld/*.html && git commit -m \"Automatic update by $USER on `hostname`\" && git push"

[clean]
exec="rm -f x/distances.html tmp/*.json tmp/instances.html tmp/*.js x/tld/*.html"